advance:
	python3 advance.py

#advance:
#	lote := $(batch)
#	ifdef lote
#		echo $(batch)
#		python3 advance.py $(batch)
#	else
#		python3 advance.py
#	endif


restart:
	python3  restart.py

simulator:
	python3  simulator.py